import { Fragment, useState } from 'react';
import { ScrollView, View } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { HelperText, TextInput } from 'react-native-paper';
import { useDispatch } from 'react-redux';
import { LocalDate } from '@js-joda/core';

import Button from '@/components/presentation/foundation/gesture-wrappers/button';
import { SurfaceText } from '@/components/presentation/foundation/surface-text';
import SessionSummary from '@/components/presentation/summary/session-summary';
import SessionSummaryTitle from '@/components/presentation/summary/session-summary-title';
import { spacing } from '@/hooks/useAppTheme';
import { usePreferredWeightUnit } from '@/hooks/usePreferredWeightUnit';
import { AiWorkoutPlan } from '@/models/ai-models';
import { ProgramBlueprint } from '@/models/blueprint-models';
import { Session } from '@/models/session-models';
import { savePlan } from '@/store/program';
import { uuid } from '@/utils/uuid';
import {
  PlanImportError,
  decodePlanCode,
  parsePlanJson,
} from '@/plugins/ai-plan-import/parse';

/**
 * "Bring your own AI" import screen: paste a plan code generated by Claude
 * (from your Health Connect data), preview it, and save it as a program.
 * Reuses the same preview + save path as the built-in AI planner.
 */
export default function ImportPlanScreen() {
  const dispatch = useDispatch();
  const { push } = useRouter();
  const preferredWeightUnit = usePreferredWeightUnit();

  const [text, setText] = useState('');
  const [plan, setPlan] = useState<AiWorkoutPlan | undefined>();
  const [error, setError] = useState<string | undefined>();

  const preview = () => {
    try {
      const parsed = parsePlanJson(decodePlanCode(text));
      setPlan(parsed);
      setError(undefined);
    } catch (e) {
      setPlan(undefined);
      setError(
        e instanceof PlanImportError
          ? e.message
          : 'Could not read this plan code.',
      );
    }
  };

  const save = () => {
    if (!plan) {
      return;
    }
    const programId = uuid();
    dispatch(
      savePlan({
        programId,
        programBlueprint: new ProgramBlueprint(
          plan.name,
          plan.sessions,
          LocalDate.now(),
        ),
      }),
    );
    push(`/settings/program-list?focusprogramId=${programId}`);
  };

  return (
    <>
      <Stack.Screen options={{ title: 'Import plan' }} />
      <ScrollView
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={{
          padding: spacing.pageHorizontalMargin,
          gap: spacing[3],
          paddingBottom: spacing[8],
        }}
      >
        <SurfaceText>
          Paste a workout plan code generated by your AI assistant from your
          Health Connect data. Preview it below, then save it as a new plan.
        </SurfaceText>

        <TextInput
          mode="outlined"
          multiline
          numberOfLines={6}
          value={text}
          onChangeText={(value) => {
            setText(value);
            setError(undefined);
          }}
          placeholder="LLPLAN1:…"
          autoCapitalize="none"
          autoCorrect={false}
          style={{ minHeight: 140 }}
        />

        {error ? (
          <HelperText type="error" visible>
            {error}
          </HelperText>
        ) : null}

        <Button
          mode="contained-tonal"
          icon="contentPasteSearch"
          onPress={preview}
          disabled={!text.trim()}
        >
          Preview plan
        </Button>

        {plan ? (
          <View style={{ gap: spacing[2] }}>
            <SurfaceText font="text-2xl" weight="bold">
              {plan.name}
            </SurfaceText>
            {plan.description ? (
              <SurfaceText>{plan.description}</SurfaceText>
            ) : null}
            {plan.sessions.map((session, i) => (
              <Fragment key={i}>
                <SessionSummaryTitle
                  session={Session.getEmptySession(session, preferredWeightUnit)}
                />
                <SessionSummary
                  session={Session.getEmptySession(session, preferredWeightUnit)}
                />
              </Fragment>
            ))}
            <Button
              mode="contained"
              icon="assignmentAdd"
              onPress={save}
              style={{ alignSelf: 'flex-end' }}
            >
              Save plan
            </Button>
          </View>
        ) : null}
      </ScrollView>
    </>
  );
}
